### ISSUE TITLE
strings

### ISSUE THREAD

**Issue by alsigna** [modemfux/n4e-python-basic-2024-homework#1]
@modemfux 

homework_task03.py 
- `output_utf = output.decode(encoding="utf-8")`, сейчас utf-8 можно не указывать, это по-умолчанию. Если какая-то другая кодировка нужна, то да, нужно указать. Но это не ошибка, просто комментарий.

- `print(f'Space symbols at start: {output_utf.startswith("\n")}')`, опять же оффтоп, но пробельные символы это не только перенос строки.

homework_task04.py
Task4.6 - первый вариант удаляет `-` и из соседа `test-server.stg` делая из него `testserver.stg`. Второй вариант да, супер.

`Т кириллицей в Ten - это опечатка?`- опечатка, наверное. Поправлю.

А в целом отлично, даже писать особо нечего. Спасибо.

**Comment by modemfux** [comment]
Спасибо за обратную связь.

`output_utf = output.decode(encoding="utf-8")` - я указал явно, исходя из требований в задании, т.к. явно был указана кодировка в которую необходимо было переводить :)

### Task4.6

Спасибо, скорректировал решение для первого варианта (но все равно, получается не гибко :)):
```
modemfux@python-vm:~/n4e/n4e-python-basic-2024-homework/013_strings [main|✔]> git diff HEAD HEAD~1
diff --git a/013_strings/homework_task04.py b/013_strings/homework_task04.py
index 383efcd..4bcb177 100644
--- a/013_strings/homework_task04.py
+++ b/013_strings/homework_task04.py
@@ -196,7 +196,7 @@ Local Interface         Exptime(s) Neighbor Interface            Neighbor Device
 10GE1/0/1                     105  10GE1/0/1                     test-server.stg
 """.strip()

-result1 = output.replace("\r\n", "\n").replace("-\n", "").replace("--", "")
+result1 = output.replace("\r\n", "\n").replace("-\n", "").replace("-", "")
 print("Task 4.6 variant 1: with replace")
 print(result1, end="\n" * 2)

```

```bash
modemfux@python-vm:~/n4e/n4e-python-basic-2024-homework/013_strings [main|✚ 1]> python3 homework_task04.py
 ...
Task 4.6 variant 1: with replace
Local Interface         Exptime(s) Neighbor Interface            Neighbor Device
100GE1/0/1                    107  100GE1/0/1                    spine1.pod1.stg
10GE1/0/1                     105  10GE1/0/1                     test-server.stg

Task 4.6 variant 2: with split and lists
Local Interface         Exptime(s) Neighbor Interface            Neighbor Device
100GE1/0/1                    107  100GE1/0/1                    spine1.pod1.stg
10GE1/0/1                     105  10GE1/0/1                     test-server.stg
 ...
```
