### ISSUE TITLE
tupples

### ISSUE THREAD

**Issue by alsigna** [modemfux/n4e-python-basic-2024-homework#2]
@modemfux 

- Task 1. кроме pop так же можно приравнять срез пустому списку, как еще один вариант
```python
In [8]: intf_list
Out[8]: ['gi0/0', 'gi0/1', 'gi0/22', 'gi0/23', 'gi0/3', 'gi0/4']

In [9]: intf_list[2:4] = []

In [10]: intf_list
Out[10]: ['gi0/0', 'gi0/1', 'gi0/3', 'gi0/4']
```

- Task2. отлично, что deque попробовали, но справа это обычный append :)

- Task4. Если хотите по пробелам разбить строку, то лучше split без аргументов использовать, справните результат 
```python
In [18]: line = " switchport  trunk   allowed"

In [19]: line.split()
Out[19]: ['switchport', 'trunk', 'allowed']

In [20]: line.split(" ")
Out[20]: ['', 'switchport', '', 'trunk', '', '', 'allowed']
```

- Task5: очень красиво с распаковкой получилось, покажу во вторник как вариант решения.

**Comment by modemfux** [comment]
Добрый день.

> Task 1. кроме pop так же можно приравнять срез пустому списку, как еще один вариант

Спасибо за совет, добавил третий вариант:

```python
In [1]: print("Task 1 variant 3 (slice and sort):")
   ...: intf_list = ["gi0/0", "gi0/1", "gi0/22", "gi0/23", "gi0/3", "gi0/4"]
   ...: intf_list[2:4] = ["gi0/2"]
   ...: intf_list.sort()
   ...: print(intf_list, end="\n\n")
Task 1 variant 3 (slice and sort):
['gi0/0', 'gi0/1', 'gi0/2', 'gi0/3', 'gi0/4']
```
> Task4. Если хотите по пробелам разбить строку, то лучше split без аргументов использовать, справните результат

Да, справедливо, спасибо. Почему-то переклинило и считал, что .split() разбивает в т.ч. и по знакам пунктуации.
