### ISSUE TITLE
dicts

### ISSUE THREAD

**Issue by alsigna** [modemfux/n4e-python-basic-2024-homework#3]
@modemfux

не знаю что написать, все отлично, спасибо!

Что бы вот такое не делать (fmt off/on), нужно просто зяпятую после последнего False  поставить и ] на новую строку перенести. У вас чуть выше при объявлении dev2_values так написано.
```python
# fmt: off
dev3_values = [
    "wlc.abcd.net",
    "192.168.1.3",
    "wlc_admin",
    "password",
    "",
    False]
# fmt: on
```

**Comment by modemfux** [comment]
Добрый день.

Спасибо за совет, скорректировал.
