### ISSUE TITLE
conditionals

### ISSUE THREAD

**Issue by alsigna** [modemfux/n4e-python-basic-2024-homework#4]
@modemfux 

task1
- прикольный и интересный подход, но если посмотреть более глобально, его сложно будет кастомизировать. Например завтра вы встретите какую нибудь ситуацию, где нужно ловить вендора, скажем по началу мака, и для него делать какую-нибудь отдельную логику. В вашем случае это сложно будет сделать, а если это будет просто решение в лоб (if/elif/else), то добавляем нужное условие и все, задача решена.

task2
- `oct` это встроенная функция, лучше другое имя использовать
- а в целом отлично, добавили проверку на валидность (пусть и первого октета только), но она есть.

task3:
- а зачем тут `print(str(config_dict.get(intf.get("mode"))).format(**intf), end=MID_END)` делать `str()`, это типа защита от отсутсвия ключа, на случай None? Если такая задача есть, тогда можно просто значение по умолчанию в get поставить `config_dict.get(intf.get("mode"), "")`, тогда если ключа нет, будет не `None` возвращаться, а пустая строка. И не будет исключения о том, что у NoneType нет метода format. С другой стороны, наверное лучше словить такое исключение и понять, что мы где-то забыли что-то прописать (добавить шаблон), чем получить пустой конфиг.

А в целом отлично, большое спасибо.

**Comment by modemfux** [comment]
Добрый день.

Спасибо за обратную связь.

По task1: замечание справедливое, спасибо. Но возникает вопрос: а не лучше ли будет тогда разнести все эти проверки по отдельным функциям, т.е. check_notation для проверки нотации, get_vendor_by_mac для поиска вендора и т.п., вызывая их в рамках отдельного скрипта в нужном нам порядке?

По task2: спасибо за замечание, забыл про такую функцию, исправил имя переменной на `oct_`.

По task3: спасибо за замечание. Да, `str` использовал как защиту от None. К сожалению, напрочь забыл о возможности выдачи нужного значения вместо дефолтного None. Скорректировал код.

**Comment by alsigna** [comment]
@modemfux 
по task1:

имел ввиду ситуация, когда у нас в рамках функции check_notation появляется какая-то дополнительная логика.
