### ISSUE TITLE
loops

### ISSUE THREAD

**Issue by alsigna** [modemfux/n4e-python-basic-2024-homework#5]
@modemfux 

task2:
- там нужно получить список из 3ех элементов `["rt1.lan.hq.net", "sw1.lan.hq.net", "dsw1.lan.hq.net"]`, т.е. отфильтровать исходный список по домены. Менять его не нужно. Добавил подробнее в текст задания.

task3:
- да, отлично, такой подход можно использовать как unrange (раскрытие сокращенного списка чего-либо, например vlans, или интерфейсов)

**Comment by modemfux** [comment]
> там нужно получить список из 3ех элементов ["rt1.lan.hq.net", "sw1.lan.hq.net", "dsw1.lan.hq.net"], т.е. отфильтровать исходный список по домены. Менять его не нужно. Добавил подробнее в текст задания.

Принято, спасибо. Поправил код:

```python
domain = "lan.hq.net"
lan_devices = [device for device in devices if domain in device]
for device in lan_devices:
    print(f"Device {device} in domain {domain}", end=MID_END)
```
